spring.application.name=springbootproject

server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/wiprotraining?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Suhass@12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
